/**
 * Runtime-validated API schemas derived from the core-api OpenAPI spec.
 *
 * Source of truth: the utoipa annotations in services/core-api/src/rest/types.rs
 * and the spec at docs/api/v1/openapi.json (generated by `cargo run -p core-api`).
 *
 * To regenerate TypeScript types from the live spec:
 *   npx openapi-typescript http://localhost:8080/api-docs/openapi.json -o src/api/types.gen.ts
 *
 * Never hand-edit this file to add types not present in the server.
 */

import { z } from 'zod'

// ── Enumerations ──────────────────────────────────────────────────────────────

export const AutosarVariantSchema = z.enum(['classic', 'adaptive'])
export type AutosarVariant = z.infer<typeof AutosarVariantSchema>

// ── Core resource schemas ─────────────────────────────────────────────────────

export const ComponentResponseSchema = z.object({
  id: z.string().uuid(),
  arxml_ref: z.string(),
  name: z.string(),
  variant: AutosarVariantSchema,
  description: z.string().optional(),
})
export type ComponentResponse = z.infer<typeof ComponentResponseSchema>

export const ListComponentsResponseSchema = z.object({
  components: z.array(ComponentResponseSchema),
  next_page_token: z.string().optional(),
  total_count: z.number().int(),
})
export type ListComponentsResponse = z.infer<typeof ListComponentsResponseSchema>

export const SearchResultResponseSchema = z.object({
  component: ComponentResponseSchema,
  score: z.number().min(0).max(1),
})
export type SearchResultResponse = z.infer<typeof SearchResultResponseSchema>

export const SearchResponseSchema = z.object({
  results: z.array(SearchResultResponseSchema),
})
export type SearchResponse = z.infer<typeof SearchResponseSchema>

export const ErrorResponseSchema = z.object({
  error: z.string(),
})
export type ErrorResponse = z.infer<typeof ErrorResponseSchema>

// ── Request types ─────────────────────────────────────────────────────────────

export type ListComponentsQuery = {
  page_size?: number
  page_token?: string
  variant?: AutosarVariant
}

export type SearchRequest = {
  query: string
  top_k?: number
}
